export const initialState = [
  {
    value: "blur",
    label: "Blur",
    defaultValue: 0,
    currentValue: 0,
    unit: "px",
    max: 10,
    listing: false,
  },
  {
    value: "brightness",
    label: "Brightness",
    defaultValue: 100,
    currentValue: 100,
    unit: "%",
    max: 200,
    listing: false,
  },
  {
    value: "contrast",
    label: "Contrast",
    defaultValue: 100,
    currentValue: 100,
    unit: "%",
    max: 1000,
    listing: false,
  },
  {
    value: "grayscale",
    label: "Grayscale",
    defaultValue: 0,
    currentValue: 0,
    unit: "%",
    max: 100,
    listing: false,
  },
  {
    value: "hue-rotate",
    label: "Hue Rotate",
    defaultValue: 0,
    currentValue: 0,
    unit: "deg",
    max: 360,
    listing: false,
  },
  {
    value: "invert",
    label: "Invert",
    defaultValue: 0,
    currentValue: 0,
    unit: "%",
    max: 100,
    listing: false,
  },
  {
    value: "opacity",
    label: "Opacity",
    defaultValue: 100,
    currentValue: 100,
    unit: "%",
    max: 100,
    listing: false,
  },
  {
    value: "saturate",
    label: "Saturate",
    defaultValue: 100,
    currentValue: 100,
    unit: "%",
    max: 1000,
    listing: false,
  },
  {
    value: "sepia",
    label: "Sepia",
    defaultValue: 0,
    currentValue: 0,
    unit: "%",
    max: 100,
    listing: false,
  },
];
